# Generated by Django 4.0.5 on 2022-06-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_stationstop_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.FloatField()),
                ('fare_type', models.IntegerField(choices=[(0, 'Base'), (1, 'Distance')], default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='stationstop',
            options={'ordering': ['route']},
        ),
    ]
