# Generated by Django 4.0.5 on 2022-07-03 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_faretable_alter_stationstop_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('birth', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='route_id',
            new_name='current_capacity',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='driver_id',
        ),
        migrations.AddField(
            model_name='bus',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='reverse',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='mainapp.route'),
        ),
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.driver'),
        ),
    ]
