# Generated by Django 4.0.5 on 2022-06-28 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(default=1, max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('driver_license', models.IntegerField(default=1)),
                ('driver_id_number', models.IntegerField(default=1)),
                ('bus_id', models.IntegerField(default=1)),
                ('start_route_at', models.CharField(default='', max_length=100)),
                ('end_route_at', models.CharField(default='', max_length=100)),
                ('location_gps', models.CharField(default='', max_length=100)),
                ('iban_number', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity', models.IntegerField(default=1)),
            ],
        ),
    ]
